INSERT INTO USER_TABLE (USER_ID,USER_NAME,USER_SEX,USER_AGE) VALUES(1,'赵一','0',20);
INSERT INTO USER_TABLE (USER_ID,USER_NAME,USER_SEX,USER_AGE) VALUES(2,'钱二','0',22);
INSERT INTO USER_TABLE (USER_ID,USER_NAME,USER_SEX,USER_AGE) VALUES(3,'孙三','1',24);