pipeline {
    agent {
        docker {
            image 'maven:3-alpine' 
            args '-v /root/.m2:/root/.m2' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                dir ("complete") {
                    configFileProvider(
                        [configFile(fileId: 'MySettings', variable: 'MAVEN_SETTINGS')]) {
                            sh './mvnw -s $MAVEN_SETTINGS clean deploy -Dregistry=https://maven.pkg.github.com/giuesposbit/gs-rest-service'
                    }
                }
            }
        }
    }
}
