pipeline {
    agent {
        docker {
            image 'maven:3-alpine' 
            args '-v /root/.m2:/root/.m2' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                dir ("complete") {
                    sh './mvnw clean package'
                    sh './mvnw deploy -Dregistry=https://maven.pkg.github.com/giuesposbit/gs-rest-service'
                }
            }
        }
    }
}
